Require Python >= 3.11
Python 3.10 does not have support for typing.Self,
so you get and error:
    ImportError: cannot import name 'Self' from 'typing'

The `typing-extension` package, version >= 4.0.0 has support:
https://typing-extensions.readthedocs.io/en/latest/index.html#Self

At the time of this writing, doing backporting work to support 3.10 is
not justified. Just get rid of it.